services:
  - type: web
    name: waterbill-api
    env: node
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr ghostscript poppler-utils && \
      npm install
    startCommand: node extractWaterBillsAPI.js
    envVars:
      - key: PORT
        value: 10000
      - key: DEBUG_DIR
        value: debug_text
      - key: UPLOAD_DIR
        value: uploads
      - key: TEMPLATE_DIR
        value: templates
